### ISSUE TITLE
Investigate correct placement of middleware for default .NET 6 templates

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/HttpCacheHeaders#100]
Default templates will probably no longer call into UseRouting / UseEndpoints.  Currently, UseCacheHeaders must be placed between these two statements.  Investigate whether to / how to update documentation in accordance with default .NET 6 template. Potentially provide a sample.  

Cfr: 

   app.MapControllers(endpoints =>
    {
        // cache headers here? 
    });

**Comment by wbuck** [comment]
Hello Kevin.
I've run in to this issue using the default dotnet 6 template and I'm curious where I should place `UseHttpCacheHeaders( )`?
Currently I've done the following:

    app.UseHttpCacheHeaders( );
    app.UseRouting( );
    app.UseAuthorization( );
    app.MapControllers( );

As you can see I explicitly call `UseRouting` which I believe is now called in the `WebApplicationBuilder`.
As per `MSDN` they mention that if we need to we can call those methods which are currently called in the `WebApplicationBuilder`.

**Comment by KevinDockx** [comment]
As mentioned by @MJomaa,  you can still call into UseRouting manually.  Yet it's not strictly necessary for the cache headers middleware.  I added a .NET 6 sample: https://github.com/KevinDockx/HttpCacheHeaders/tree/master/sample/Marvin.Cache.Headers.Sample.NET6 :)
