### ISSUE TITLE
Support injecting custom store for validation/ETags

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/HttpCacheHeaders#11]

**Comment by KevinDockx** [comment]
Needs design

**Comment by maartenba** [comment]
Should this be as a function returning an `IValidationValueStore` or as an instance? Or will users just register the service themselves and be done with it (skipping service collection `.AddHttpCacheHeaders`)

**Comment by KevinDockx** [comment]
I was thinking of something along the lines of how JsonOptions can be used to set a custom contract resolver, eg: 
  services.AddMvc(...)
  .AddJsonOptions(options => options.SerializerSettings.ContractResolver = 
             **new CamelCasePropertyNamesContractResolver()**); 

But I'm open to suggestions, what do you think? :)

**Comment by maartenba** [comment]
That's what the service collection is for imo :-) Although that sucks for discoverability. I'd go with either a function that instantiates things, or just take an instance much like the above example.

**Comment by CumpsD** [comment]
Proposal to implement this by passing in an instance of a custom store: https://github.com/KevinDockx/HttpCacheHeaders/pull/57

**Comment by KevinDockx** [comment]
@CumpsD : I pushed a few commits to the modular branch - let me know what you think :)  If those are ok for you I think we can merge this into master.

**Comment by KevinDockx** [comment]
Been thinking about this some more (it's amazing what an awful night of sleep in terrible temperatures can do).  I think it's best to add a StoreKeyContext (or something along those lines) object and accept that as parameter for GenerateStoreKey.   That allows us to add additional info to the context in case it's needed in a later version without breaking changes.    I'll add another commit for that today :)

**Comment by CumpsD** [comment]
Commits look good to me, StoreKeyContext sounds good too, can't wait for the next release :D

**Comment by KevinDockx** [comment]
Added the context, merged branch into master and just pushed a prerelease version to NuGet :)

**Comment by CumpsD** [comment]
Using prerelease, seems to all work :)
