### ISSUE TITLE
Use the IAsyncEnumerable interface in the FindStoreKeysByKeyPartAsync method of the IValueStore interface

### ISSUE THREAD

**Issue by SeanFarrow** [KevinDockx/HttpCacheHeaders#113]
Given this is a major release, we should look at using hte IAsyncEnumerable interface when returning keys from the FindStoreKeysByKeyPartAsync method of the IValueStore validator.

Whilst this won't help im-memory implementations, it will help any distributed cache implementations.

**Comment by KevinDockx** [comment]
Yep - I'll take this up :)

**Comment by SeanFarrow** [comment]
OK, I can have a PR for you later today—I need this for the distributed cache anyway, so it makes sense just to do it as part of that work?

**Comment by KevinDockx** [comment]
(I was already working on it anyway :))
