### ISSUE TITLE
Allow StoreKey to be rehydrated

### ISSUE THREAD

**Issue by SeanFarrow** [KevinDockx/HttpCacheHeaders#114]
Currently, it is not possible to rehydrate a StoreKey in it's entirity as we are only creating a string witht the values in.

We need this for issue #112. As well as this, it may mean we can remove the use of a second dictionary in the in-memory implementation of IValueStore in the future.

**Comment by KevinDockx** [comment]
What would be needed to make this possible?  My main concern is breaking outer facing stuff, so if it doesn't I'd be inclined to go for it :)

**Comment by SeanFarrow** [comment]
I don’t think removing the second dictionary will break outer facing stuff, but it’s not something I’d be looking at for this release.
In terms of what needs serializing, we need to serialize both the key/value in a key/value pair to the final string, currently only the values are serialized and joined.

The only other alternative is to have a type that derives from KeyStore for the distributed stores and do the serialization required there.

I’m open to either approach.

**Comment by KevinDockx** [comment]
Serializing both is ok as far as I'm concerned, gives us a unified approach.  Do you need me to do that, or will you take this up?

**Comment by SeanFarrow** [comment]
It depends when you want to get v7 out, I’m not going to get to this before Tuesday as we’re just doing a release.
I’m happy to do it though if your not in a rush as I’m blocked without it really!
Thanks

**Comment by KevinDockx** [comment]
There's no rush :)

**Comment by SeanFarrow** [comment]
OK, I’ll stick this on my list.

**Comment by KevinDockx** [comment]
Hi Sean, do you happen to have an idea of when you'll be able to work on this PR?  Thanks! :)

**Comment by SeanFarrow** [comment]
I have some holiday after the 05/05, so I’m hoping to work on it then.

Thanks,
Sean.

**Comment by KevinDockx** [comment]
That sounds good, thanks!

**Comment by SeanFarrow** [comment]
@KevinDockx  Do we want to spin up a Docker container for Redis in the tests to check that we can retrieve the keys a user would expect given the pattern we are matching and whether we are ignoring case?

I ask as to retrieve the keys, we have to look at each server, which unfortunately doesn't have  an interface, so this isn't really mockable.

**Comment by KevinDockx** [comment]
I you wish, sure, but I wouldn't go that far - seems like a bit of overkill just to get a few additional automated tests.

**Comment by SeanFarrow** [comment]
I've now raised a PR for this.

Once this is merged, I can finish off #112.

**Comment by SeanFarrow** [comment]
Closed by #115
