### ISSUE TITLE
Remove all unsupported tfm's

### ISSUE THREAD

**Issue by SeanFarrow** [KevinDockx/HttpCacheHeaders#116]
Ideally, it would be nice if we removed all unsupported tfm's from version 7.

This means we would end up supporting .net 6 and 7 and then adding .Net 8 when it was released.

I'm happy to take this if it makes sense.

**Comment by KevinDockx** [comment]
Yep, at this moment in time that sounds like a good idea :)

**Comment by SeanFarrow** [comment]
I'm just finishing this and have noticed we have two sln files:
Marvin.Cache.Headers.All.sln 
and 
Marvin.Cache.Headers.All.sln
Do we need both of these?
Should we delete the Marvin.Cache.Headers.sln file and just have one?
