### ISSUE TITLE
Update all out-of-date NuGet packages

### ISSUE THREAD

**Issue by SeanFarrow** [KevinDockx/HttpCacheHeaders#117]
For v78 we should ideally update all out-of-date NuGet packages.

I'm happy to take this as it isn't that much work.

Ideally though, long-term we should use something like Dependabot to keep packages up-to-date.

**Comment by KevinDockx** [comment]
As long as it doesn't result in being unable to support .NET versions we still want to support, this is fine by me.  Thanks Sean, you're doing a lot of work on this, it's much appreciated!

**Comment by SeanFarrow** [comment]
My view is we should support everything that is current?
I.e, .Net 6+.
If you agree, can you assign me to this please?
Thanks,
Sean.

**Comment by SeanFarrow** [comment]
Do we want to use .net 6 or 7 as the major version for packages?

**Comment by KevinDockx** [comment]
I'd go for the latest LTS version, so: .NET 6.

**Comment by SeanFarrow** [comment]
I'm thinking we should multi-target this properly and use .net 7 packages for the .Net 7.0 target and .Net 6 packages for the .Net 6 target.

We shouldn't have any issues with this as we are not really using anything that differs in either functionality or method signatures.

**Comment by KevinDockx** [comment]
Good point - that's a better idea :-)
