### ISSUE TITLE
Support Pragma

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/HttpCacheHeaders#12]

**Comment by maartenba** [comment]
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.32, this can be a simple copy of the values of the cache-control header?

**Comment by KevinDockx** [comment]
I'm not sure on how to interpret it, at least not for responses.  If I understand correctly, it's used by caches if the client sends Pragma: no-cache (for backwards compat).  But this middleware doesn't cache on its own, so the question it: what should we send in a possible Pragma response header 1) when a client sends a pragma request header, and 2) when a client doesn't send such a header?

Cfr: http://stackoverflow.com/questions/10314174/difference-between-pragma-and-cache-control-headers (last answer, also not completely sure apparently :)) 

So question is: do we need to include this at all?  Maybe set it to "no-cache" if that option is chosen on the ValidationModelOptions?

**Comment by maartenba** [comment]
Reading through the spec again I think either make it no-cache when that is set, or copy the value from Cache-Control.

**Comment by KevinDockx** [comment]
I'd go for no-cache in that case.  Looks weird that a feature intended for backwards compat (HTTP 1 vs 1/1) would support all the Cache-Control directives.

**Comment by maartenba** [comment]
Can be closed I think :)

**Comment by KevinDockx** [comment]
Yup :)
