### ISSUE TITLE
Should we migrate away from Moq

### ISSUE THREAD

**Issue by SeanFarrow** [KevinDockx/HttpCacheHeaders#120]
Given what is going on with Moq, should we consider migrating to something like NSubstitute?
If yes, I'm happy to do the work.

**Comment by KevinDockx** [comment]
I wasn't aware of the controversy surrounding Moq :)  I had a look, and TBH: I'd wait and see what happens with that project / the team behind it before making a decision to migrate to something else.  Stuff like this tends to calm down and ease out once the initial shock/reactions are put into context :)
