### ISSUE TITLE
Use the InMemoryCache rather than a custom dictionary

### ISSUE THREAD

**Issue by SeanFarrow** [KevinDockx/HttpCacheHeaders#123]
It hames sense to use the InMemoryCache rather than our own custom dictionaries now that we serialize the keys using Json.

We shouldthough keep a list/set of keys we have currently cached for expediency.

**Comment by SeanFarrow** [comment]
@KevinDockx 

Can you have a look at branch feature/sf/123-use-inmemory-cache please.
the fork is [here](https://github.com/SeanFarrow/HttpCacheHeaders.git).

I've got the InmemoryValidatorValueStore using an IMemoryCache in tests, but for some reason 7 tests in the DefaultConfigurationFacts class fail.

I've added the memory cache to DI, so can't see where this is going wrong.
Thanks,
Sean.

**Comment by KevinDockx** [comment]
Hi Sean, thanks - bit busy this week, I've put it on my agenda for Monday :)

**Comment by SeanFarrow** [comment]
No worries, I’ll finish off the Redis stuff his weekend.

**Comment by KevinDockx** [comment]
I had a look: the tests were crashing because of a nullref exception on the _cache variable in the InMemoryValidatorValueStore (e.g.: when trying to get something from the cache).  The reason was that the AddValidatorValueStore extension method in ServicesExtensions didn't pass an IMemoryCache instance when newing up the InMemoryValidatorValueStore.  The fix =>

```
private static void AddValidatorValueStore(
    IServiceCollection services,
    Func<IServiceProvider, IValidatorValueStore> validatorValueStoreFunc)
{
    if (services == null)
    {
        throw new ArgumentNullException(nameof(services));
    }

    if (validatorValueStoreFunc == null)
    {
        validatorValueStoreFunc = services => new InMemoryValidatorValueStore(
            services.GetRequiredService<IMemoryCache>(),
            services.GetRequiredService<IStoreKeySerializer>());
    }

    services.Add(ServiceDescriptor.Singleton(typeof(IValidatorValueStore), validatorValueStoreFunc));
}
```


With this the tests no longer crash, so you should be able to continue :-)  That said, they still fail.  Haven't investigated that further, I assume the implementation wasn't ready yet.  If you're stuck, let me know and I'll have a look.

**Comment by SeanFarrow** [comment]
OK, I’ve fixed the issue with the tests not constructing the InMemoryValidatorValueStore from DI, but I can’t see why the tests still fail.
All the implementation is pretty much done, the only thing left to do is move to using a hashset for the key store, rather than a dictionary.
If you can have a look at this, I’ll finish off the Redis stuff.

**Comment by SeanFarrow** [comment]
I now have time to look at this, so don’t worry about this at your end.

I’ll hopefully have PR’s for you at the weekend.

**Comment by KevinDockx** [comment]
Oh that's great, thanks!  I have blocked some time next week to have a look at the PRs in case you find the time.

**Comment by SeanFarrow** [comment]
OK, I’m just about to raise a PR for this.

I’ve not added any extra tests, just got things working with the existing tests.
I’ll put an issue in to add more tests across the board, but we can do this after the next release.
The integration tests all pass.
I’ll wait for you to merge this to finish the Redis stuff, but will add other issues in the meantime—NuGet package upgrades for .Net 8 and CancellationToken support.

**Comment by KevinDockx** [comment]
Merged! :)
