### ISSUE TITLE
Support If-None-Match *

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/HttpCacheHeaders#25]
The meaning of "If-None-Match: *" is that the method MUST NOT be performed if the representation selected by the origin server (or by a cache, possibly using the Vary mechanism) exists, and SHOULD be performed if the representation does not exist. This feature is intended to be useful in preventing races between PUT operations.

Cfr: https://tools.ietf.org/html/rfc2616#page-132

**Comment by rydes** [comment]
Hi. I would like to work on this issue.

**Comment by KevinDockx** [comment]
@rydes: thanks, feel free! :)

**Comment by KevinDockx** [comment]
If you're ok with this, just send a PR when you're done (+ unit tests for this specific PR), and I'll have a look.  If you've got any questions, don't hesitate to ask :)

**Comment by KevinDockx** [comment]
Hi @rydes, I guess you couldn't find the time to work on this.  In the meanwhile I fixed this issue - if there's something else you'd like to work on, feel free :)
