### ISSUE TITLE
Allow multiple datetime formats?

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/HttpCacheHeaders#29]
Currently, we only try to parse to/from RFC1123 pattern (https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx).  

Should we allow multiple formats?  Cfr https://msdn.microsoft.com/en-us/library/bb301210(v=vs.110).aspx

**Comment by CumpsD** [comment]
I don't dare to say it, but let's also make it configurable in #57? ;)

**Comment by CumpsD** [comment]
This commit should fix this issue: https://github.com/KevinDockx/HttpCacheHeaders/pull/58/commits/8f99e87e3955ea9480ab8aaac9112bdad7b68b89

It allows you to configure your own dateparser for every possible conversion we need to do. I've left it very flexible to not simply provide 1 formatting option for all our conversion, but made them explicit in case people have weird implementation details where they need to parse a last modified differently from an outgoing expires.
