### ISSUE TITLE
Unable to install on Asp.NET Core (Full .NET)

### ISSUE THREAD

**Issue by Rajivhost** [KevinDockx/HttpCacheHeaders#37]
Hi,
this is what I get once I tryed to install the packages on my Asp.NET Core (Full .NET) project.

![image](https://cloud.githubusercontent.com/assets/3539984/26833475/7b4bfd1a-4aca-11e7-839b-691100369d73.png)

**Comment by KevinDockx** [comment]
You'll need a version of the .NET framework that implements the .NET Standard 1.6 or higher.  Have a look at this to know which platforms implement that: https://docs.microsoft.com/en-us/dotnet/standard/net-standard
