### ISSUE TITLE
Provide an option to include Access-Control-Expose-Headers in the response header

### ISSUE THREAD

**Issue by carganilla** [KevinDockx/HttpCacheHeaders#38]
Although the ETag header is included in the response, it cannot be accessed thru JavaScript when hosted from a different domain (foreign origin). According to a post in StackOverflow located at [https://stackoverflow.com/a/25673446/4997224](https://stackoverflow.com/a/25673446/4997224), there is a need to include the `Access-Control-Expose-Headers` to give explicit permissions for the client to read headers like the ETag header.

Here's what I did in my local copy of the HttpCacheHeaders. I added the last line of code after the code that sets/adds the ETag header and it seems to solve my problem. Unfortunately, the `Access-Control-Expose-Headers` string is not defined in the `HeaderNames` class so I had to hard-code it here.

````csharp
// set the ETag header
headers[HeaderNames.ETag] = eTag.Value;
// expose ETag header over CORS
headers["Access-Control-Expose-Headers"] = "etag";
````

It would be nice if we can make this configurable.

**Comment by KevinDockx** [comment]
This sounds like something that should be the responsibility of another piece of middleware - maybe MS's CORS middleware can handle this?  Adding this would be easy, but I feel it goes beyond the scope of what Marvin.Cache.Headers is trying to achieve: generating headers related to caching, not related to permissions.
