### ISSUE TITLE
app.UseDeveloperExceptionPage() issue

### ISSUE THREAD

**Issue by dotnetshadow** [KevinDockx/HttpCacheHeaders#43]
Hi there,

I found that if I have an error in my application and I use the following order in startup:

```
app.UseDeveloperExceptionPage(); 
app.UseHttpCacheHeaders();
app.UseMvc();
```

I get a blank page instead of the exception details in the page. 

If I use the following order then everything works correctly:
```
app.UseHttpCacheHeaders();
app.UseDeveloperExceptionPage(); 
app.UseMvc();
```

Could you please clarify the ordering needed, or perhaps your middleware needs to be bypassed when  an error occurs?

**Comment by KevinDockx** [comment]
The DeveloperExceptionPage middleware should be first in the request pipeline afaik.  For now your workaround seems to work, but I'll investigate further why this behaviour is happening.   Thanks for letting me know!

**Comment by KevinDockx** [comment]
Added a (manual) test for this, issue seems to be solved.

**Comment by dotnetshadow** [comment]
@KevinDockx I haven't checked for a while, when you say issue seems to be solved, do you mean it doesn't matter about the order anymore?
