### ISSUE TITLE
Allow customer Last-Modified

### ISSUE THREAD

**Issue by toddb** [KevinDockx/HttpCacheHeaders#51]
I have resources that I know the last modified (which is not the time of generation) and I want to return this.

> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified
>
>The Last-Modified response HTTP header contains the date and time at which the origin server believes the resource was last modified. It is used as a validator to determine if a resource received or stored is the same. Less accurate than an ETag header, it is a fallback mechanism. Conditional requests containing If-Modified-Since or If-Unmodified-Since headers make use of this field.

**Comment by KevinDockx** [comment]
I suppose you're talking about a fixed value for a specific resource?  If yes, maybe that functionality could be added via an attribute at action (resource) level.

**Comment by KevinDockx** [comment]
This is now possible via the ILastModifiedInjector.  See PR https://github.com/KevinDockx/HttpCacheHeaders/pull/66 for details.
