### ISSUE TITLE
Allow custom GenerateKey method

### ISSUE THREAD

**Issue by CumpsD** [KevinDockx/HttpCacheHeaders#53]
https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/HttpCacheHeadersMiddleware.cs#L610

I would like to create a PR which allows a user to pass in his own method to create the key (which is later passed to the Store).

This would allow people to decide which values they like to take into account (and possibly modify).

**Comment by KevinDockx** [comment]
Been thinking about this - this seems to be related to #6 and #22.  It's quite dangerous to allow this with how the code currently works: the key generated by this method is combined with the request body when generating a strong eTag.  If we allow a user to change this we can no longer guarantee that the eTag is effectively strong.  What's the reason you want to allow this?  

Maybe we should combine a few issues :) If we would allow users to inject their own eTag generator (strong or weak), we could provide our own default implementation (strong eTag, key = headers + path, etag gets generated from key + body) and allow people to inject custom implementations (for both weak and strong etags).  Would require a big red warning somewhere to ensure they don't accidentally create a function that results in a weak eTag when they want a strong Etag :) 

What do you think?

**Comment by CumpsD** [comment]
Use case:
* `/v1/gemeenten/11057--text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8-gzip; q=0.9-deflate; q=0.1-br; q=1.0`
* `/v1/gemeenten/11057--text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.7-gzip; q=0.9-deflate; q=0.1-br; q=1.0`
* `/v1/gemeenten/11057--text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.4-gzip; q=0.5-deflate; q=0.1-br; q=1.0`

These 3 keys would result in different ETags and lookups, while it's really the same. Especially in our application, where I know more details about the domain. I can reduce the above to:

* `/v1/gemeenten/11057--application/xml`

Since that is the only differentiation we support in our application (xml or json), we will never return html, xhtml or anything else. So I can reduce a lot of pointless entries in our store, and have more cache hits.

We could indeed solve all of this by allowing injecting all moving parts and providing defaults. That would give the most flexibility, and is a good idea tbh. It would support sane defaults out of the box, while allowing extensions points for more advanced usage.

**Comment by KevinDockx** [comment]
Couldn't that use case be solved by changing the VaryBy headers for that specific resource so not all of them are taken into account? 

Regardless: the extension points should be created sooner or later, so why not now ;-)

**Comment by CumpsD** [comment]
No, because the qualities are in the header. So you actually want the header in the VaryBy, but you don't want every byte of it ;)

To give you an idea of a snippet I have:

```
        public static AcceptType DetermineAcceptType(this RequestHeaders requestHeaders)
        {
            var headersByQuality = requestHeaders.AcceptEncoding.OrderBy(x => x.Quality);

            foreach (var headerWithQuality in headersByQuality)
            {
                if (!headerWithQuality.Value.HasValue)
                    continue;

                if (headerWithQuality.Value.Value.ToLowerInvariant().Contains("xml".ToLowerInvariant()))
                    return AcceptType.Xml;

                if (headerWithQuality.Value.Value.ToLowerInvariant().Contains("ld+json".ToLowerInvariant()))
                    return AcceptType.JsonLd;

                if (headerWithQuality.Value.Value.ToLowerInvariant().Contains("json".ToLowerInvariant()))
                    return AcceptType.Json;
            }

            return AcceptType.Json;
        }
```
