### ISSUE TITLE
Change requestkey from string to custom type

### ISSUE THREAD

**Issue by CumpsD** [KevinDockx/HttpCacheHeaders#54]
https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/HttpCacheHeadersMiddleware.cs#L610

Before doing #53 I would like to create which changes the string from the key to a type containing properties for the separate parts (and a custom ToString which returns the same as today)

This gives a bit more flexibility in future changes

**Comment by KevinDockx** [comment]
See comments in #53 :)  As far as this specific issue is concerned: maybe this should return a dictionary with key/value pairs for the parts?  Would allow a lot of flexibility.

**Comment by CumpsD** [comment]
I'll already make this change, which can then in #53 be extracted into a default + injectable things.

**Comment by KevinDockx** [comment]
Merged!
