### ISSUE TITLE
Question: Why update Last-Modified when found in store?

### ISSUE THREAD

**Issue by CumpsD** [KevinDockx/HttpCacheHeaders#55]
https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/HttpCacheHeadersMiddleware.cs#L85

I am trying to understand, why are we updating the Last Modified in the store? Shouldn't we let the store decide this?

Given an empty store and an initial request:
* Checks occur for caching
* None match, request goes as normal, response is built
* ETag is calculated and last modified is UtcNow
* This gets stored in the store and the response is sent

Given previous with a request for the same
* Checks for cache occur
* Found in store
* Update Last Modified in store
* Send back 302 not modified with a different last modified

Why are we doing the update? Image I have a redis store, and I want the last modified date be updated by another process, which knows a lot better when the object itself has changed (smarter cache invalidation), this would get overwritten now. Does that make sense?

**Comment by KevinDockx** [comment]
The more I think about it the closer I'm coming to the conclusion that the Last-Modified date (and eTag) shouldn't be updated in ValidationValueStore.  By doing that I'm essentially regenerating the validators (Last-Modifed, ETag) while nothing has changed.  I'll let this sink in a bit further, but I think you've found a bug :)

**Comment by KevinDockx** [comment]
Upon further investigation: Last-Modified & ETag should not be updated when a 304 is returned.  Will fix.

**Comment by CumpsD** [comment]
The fix is in modularcomponents by the way :)

**Comment by KevinDockx** [comment]
You write code faster than I can look at it :-)  Tnx!
