### ISSUE TITLE
Allow custom ETag functions

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/HttpCacheHeaders#6]

**Comment by KevinDockx** [comment]
Needs design

**Comment by KevinDockx** [comment]
Should be for weak etags only (strong etags should take headers & body into consideration, weak etags can differ)

**Comment by CumpsD** [comment]
This would probably also be one of the parts to be configurable in https://github.com/KevinDockx/HttpCacheHeaders/pull/57

**Comment by CumpsD** [comment]
This commit extracts the current generator and makes it pluggable: https://github.com/KevinDockx/HttpCacheHeaders/pull/58/commits/b706fe4b391937ca0a677ebfb617debd49a21ed9 Need to let it sink in a little to think about the signature to `GenerateETag()`
