### ISSUE TITLE
Provide HttpContext to IETagGenerator.GenerateETag 

### ISSUE THREAD

**Issue by tomseida** [KevinDockx/HttpCacheHeaders#65]
I think it would be helpful if the GenerateETag method in the IETagGenerator received the HttpConext.

I am currently working on an API that uses CosmosDb as its persistence layer. CosmosDb generates ETags for all documents and the CUD methods can be provided ETags. I would like to use these ETags in place of those generated by your default technique. If HttpContext was provided, I would let my action method, or an action filter, insert the ETag into the HttpContext.Items dictionary element (e.g., HttpContext.Items.Add("ETag", eTag);). In the GenerateETag, I would check the context Items dictionary for the "ETag" key, if it exists, I would use that value. If not, use the default generator.

**Comment by KevinDockx** [comment]
Feature implemented via ILastModifiedInjector.  Closing this, see PR https://github.com/KevinDockx/HttpCacheHeaders/pull/66 for details.
