### ISSUE TITLE
Set Last Modified after Store has been consulted

### ISSUE THREAD

**Issue by CumpsD** [KevinDockx/HttpCacheHeaders#68]
Right now we have:
https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/HttpCacheHeadersMiddleware.cs#L456-L459

Wouldn't it make more sense to move this code to https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/HttpCacheHeadersMiddleware.cs#L469 and also pass in `savedResponse`? Then the injector has more to work with.

**Comment by CumpsD** [comment]
See #69 as a suggestion

**Comment by CumpsD** [comment]
My use case for this:
I want the Last Modified populated with the value in the ValidatorValue, not just DateTime Now.
When saving (_store.SetAsync) I am fine with it using DateTime Now, so basically I have 2 types of "CalculateLastModified", one when setting (which is datetime now) and one when sending back the response in the headers (the value which was used when setting, not by default always datetime now)

**Comment by KevinDockx** [comment]
Hi David,

sounds like a valid use case :)  But wouldn't it make sense to add the ValidatorValue (savedResponse) you need as a property to ResourceContext?  Like that the contract (ILastModifiedInjector) doesn't have to change.  

By the way: I'm considering making ResourceContext sealed; doesn't seem like it would be something someone should be allowed to derive from.  Thoughts?

**Comment by CumpsD** [comment]
I didn't want to make it an additional property since you don't always have it available. Unless you are fine with it being `null` from time to time?

Sealed is fine by me.

**Comment by KevinDockx** [comment]
Fine by me :)

**Comment by CumpsD** [comment]
PR updated

**Comment by KevinDockx** [comment]
Merged

**Comment by CumpsD** [comment]
Thanks! Any timeframe on next release? :)

**Comment by KevinDockx** [comment]
Here you go: https://www.nuget.org/packages/Marvin.Cache.Headers/3.2.0 :)
