### ISSUE TITLE
Implement cache-control configuration at resource level instead of global

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/HttpCacheHeaders#7]

**Comment by KevinDockx** [comment]
Needs design.  Attributes?  Config mappings?

**Comment by CumpsD** [comment]
Attributes is probably the more friendly approach, on the controller action method

**Comment by KevinDockx** [comment]
Attributes on the controller actions would be my first choice but I don't think that's possible with the way middleware works.  Afaik you can't access route data (and thus read out the attribute) from the middleware as route data is an MVC feature.  The cache headers middleware (and other pieces of middleware) don't know about the MVC middleware nor have access to it.  If you happen to know of a way to achieve this, let me know :-)

I see two alternatives: one would be using config mappings at cache headers middleware level, ie: you'd have to provide cache control options for each URI (for which you want cache control to be different from the global config) when setting up the cache headers middleware in ConfigureServices.  Providers could be written to read this from a config file, a database, ...

The second alternative is creating a ResourceFilter attribtue (https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1) which takes care of generating the cache headers etc - but that means "duplicating" the logic for this in that attribute.   

Or, as a 3rd alternative: support both :-)

What do you think?

**Comment by CumpsD** [comment]
Have a look at #48 using attributes

**Comment by KevinDockx** [comment]
Renamed some properties as discussed, will be part of 2.0 release :)

**Comment by CumpsD** [comment]
Thanks! Upgrading now :)

**Comment by CumpsD** [comment]
Is it possible some more need to be renamed?

https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/ExpirationModelOptions.cs#L43
https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/ExpirationModelOptions.cs#L52

**Comment by KevinDockx** [comment]
Obviously not my smartest moment :-)  Fixed, release 2.0.1 is on NuGet.
