### ISSUE TITLE
Can't use HttpCacheValidationAttribute.Vary

### ISSUE THREAD

**Issue by DeLeneMirouze** [KevinDockx/HttpCacheHeaders#75]
Hi

Could you provide a demo for the HttpCacheValidationAttribute.Vary?
This is refused by the compiler:

`[HttpCacheValidation(MustRevalidate = false, Vary = new [] { "OrderBy" })]`

> CS0655	'Vary' is not a valid named attribute argument because it is not a valid attribute parameter type

I don't really know why

**Comment by KevinDockx** [comment]
Thanks for noticing this.  The attribute property Vary is of type IEnumerable<string>, and apparently that's not an allowed type for attribute properties.  I switched it to a array of string, which is allowed, see https://github.com/KevinDockx/HttpCacheHeaders/commit/f1a39bf457496e2ef58b34efb06253aa30d5f8ab

**Comment by CumpsD** [comment]
Looking forward to this release :)

**Comment by VanHuychemG** [comment]
Looking forward to a quick release ;), just stumbled upon this one too.

**Comment by KevinDockx** [comment]
I seem to feel a bit of pressure for this one... ;-)  Just pushed it to NuGet, should be visible in a few minutes :-)

**Comment by CumpsD** [comment]
Thanks :p
