### ISSUE TITLE
Does it work on AspNetCore 3.0?

### ISSUE THREAD

**Issue by tonibabieka** [KevinDockx/HttpCacheHeaders#81]
Does it work on Aspnetcore 3.0 or even 3.1 and IIS?

When I run it and log the request and the response ETag is set, but new request from the remote browser have any "if-none-match" header.

Can it be an IIS issue or there is any server and IIS configuration matter?

Thanks.

**Comment by KevinDockx** [comment]
Yes, it works on & is tested with ASP.NET Core 3.  I used it in a few places, one of those can be found here: https://github.com/KevinDockx/ImplementingAdvancedRESTfulConcernsAspNetCore3

It's the responsibility of the client that sends the request afterwards to correctly set those headers, and any component in between the browser & the API can potentially change those, from the browser over IIS to a reverse proxy, firewall, in-between caches, ... I have no control over that...
