### ISSUE TITLE
Will it work as a replacement of outputcache where location is set as ServerAndClient

### ISSUE THREAD

**Issue by rajdey1** [KevinDockx/HttpCacheHeaders#91]
Hi,

I am migrating a asp.net project to asp.net core. In the asp.net project we cache  MVC view using the outputCache where in the settings is **[OutputCache(Duration = 900, VarByParam ="*", Location ="ServerAndClient")]**  I believe since the location is ServerAndClient it will work on generated Etag in asp.net but since asp.net core there is no generated Etag. Can I use HttpCacheHeaders middleware and achieve the same. 

If yes how do we configure the same?

**Comment by KevinDockx** [comment]
This middleware is not a cache store, it simply generates cache headers (including Etags).  You'll still need a cache store, preferably a separate cache server, to actually cache stuff.
