### ISSUE TITLE
IValidatorValueInvalidator implementation

### ISSUE THREAD

**Issue by patelbinal** [KevinDockx/HttpCacheHeaders#94]
Hi Team,

Suppose my particular resource gets updated by the backend job. Now, my resource gets stale which is exposed by API. So, how will IValidatorValueInvalidator help to invalidate the cache for this entire resource?

If I mark the keys invalid related to this resource by IValidatorValueInvalidator, will the next request to any of the endpoint be served by the Server, not from the cache?

**Comment by patelbinal** [comment]
Also, can you please explain more on the difference between FindByCurrentResourcePath and FindByKeyPart methods of IValidatorValueInvalidator?

**Comment by KevinDockx** [comment]
Hi,

that's indeed the idea.  When marking something for invalidation, that item (stored metadata) is removed from the internal store.  On a subsequent request to the same resource the metadata will not be available in the internal store, resulting in the exact same logic as if it were a first request.  

FindByKeyPart searches the internal store for keys of which the inputted value partially matches.  Those keys can then be marked for invalidation. You can find an example of that here: https://github.com/KevinDockx/HttpCacheHeaders/blob/master/sample/Marvin.Cache.Headers.Sample/Controllers/StoreManipulationController.cs#L72
FindByCurrentResourcePath  searches the internal store for keys which (partially) match the current resource path.  This method internally calls FindByKeyPart.  

Hope this helps! :)

**Comment by patelbinal** [comment]
Thanks
