### ISSUE TITLE
VaryByQueryKeys cache validation

### ISSUE THREAD

**Issue by fp-jcorriveau** [KevinDockx/HttpCacheHeaders#96]
How do we validate Query Parameters ?

Example when using ResponseCacheAttribute :

[ResponseCache(Duration = 120, VaryByQueryKeys = new[] { "PageNumber", "PageSize" })]

**Comment by KevinDockx** [comment]
What scenario are you trying to achieve?  Vary headers can be set in the validation model options, but there's no such thing as "VaryByQueryKeys" as each change in querystring key/value will automatically result in a new eTag.

**Comment by fp-jcorriveau** [comment]
When using ResponseCache Attribute and adding query parameters like PageNumber and PageSize, the result of the query is cached by PageNumber/PageSize values.

When I use HttpCacheHeaders, if one of the query parameter value change, the result of the query never change.
Then if it's been cached using PageNumber=1&PageSize=10, if I ask PageNumber=2, I will still receive page 1...

I don't know if I'm clear enough, I feel like I can't explain very well...

**Comment by KevinDockx** [comment]
Hmm, that's very strange - the key that is used by HttpCacheHeaders is calculated from, amongst others, the query string: https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/DefaultStoreKeyGenerator.cs#L49 - so: different query string values should result in a different key, and thus a different eTag.  

Would you happen to have a small code sample in which the issue happens?  I'll have a look :)

**Comment by fp-jcorriveau** [comment]
Hmm.. I might have made something wrong...
Here is a demo project I've built following your pluralsight courses
https://drive.google.com/file/d/1kTRjMcOKO8ycC7Q8Z-RhDzrgoeOzFR2_/view?usp=sharing

**Comment by KevinDockx** [comment]
Hi, 

I had a look. I tested with the api/etablissements endpoint (turned off authentication for testing as I don't have an account on your AD :)).  

First request:
http://localhost:51044/api/etablissements?page=1&size=10
=> new response generated. 

Second request:
http://localhost:51044/api/etablissements?page=1&size=15
=> different URI, but: the same response is returned & the eTag is the same.  

Then I tried this again, but I first disabled your cache store (the response caching middleware).  This time, the two requests result in 2 different responses with different eTags being served.  That leads me to conclude that marvin.cache.headers correctly takes the query string into account, but the response caching middleware doesn't: when the response caching middleware is enabled, the second request doesn't hit marvin.cache.headers.  Instead, the response is served up from your cache store.  

You can tell the response caching middleware to take your query string parameters into account as such (like you did in your example): 

[HttpGet(Name = Route.GetEtablissementsList)]
[HttpHead]
[ProducesResponseType(StatusCodes.Status200OK)]
**[ResponseCache(Duration = 60, VaryByQueryKeys = new string[] {"Page", "Size"})]**
public ActionResult<IEnumerable<GetEtablissementsListModel>> GetEtablissements(
            [FromQuery] Paging parameters)
			
As marvin.cache.headers automatically takes all query string parameters into account (and Page & Size are the only two), this will result in both middlewares working nicely together :)

Small tip: I'd suggest not using the response cache middleware.  It's only a partial implementation of the Http Cache standard which tends to result in a less performant cache.  It's better to use a separate cache server or CDN that correctly implements the Http Cache standard.  If you use one of those approaches, all you'll need in your API is the marvin.cache.headers middleware - the cache server will take care of the rest.

Bonne chance! ;-)

KR,
Kevin

**Comment by fp-jcorriveau** [comment]
Merci beaucoup! 😉


Jonathan Corriveau
Architecte organique
Services informatiques - équipe Priorx
[Familiprix]<https://www.familiprix.com/fr>

De : Kevin Dockx ***@***.***>
Envoyé : 7 avril 2021 10:34
À : KevinDockx/HttpCacheHeaders ***@***.***>
Cc : Corriveau, Jonathan ***@***.***>; Author ***@***.***>
Objet : Re: [KevinDockx/HttpCacheHeaders] VaryByQueryKeys cache validation (#96)


I had a look. I tested with the api/etablissements endpoint (turned off authentication for testing as I don't have an account on your AD :)).

First request:
http://localhost:51044/api/etablissements?page=1&size=10
=> new response generated.

Second request:
http://localhost:51044/api/etablissements?page=1&size=15
=> different URI, but: the same response is returned & the eTag is the same.

Then I tried this again, but I first disabled your cache store (the response caching middleware). This time, the two requests result in 2 different responses with different eTags being served. That leads me to conclude that marvin.cache.headers correctly takes the query string into account, but the response caching middleware doesn't: when the response caching middleware is enabled, the second request doesn't hit marvin.cache.headers. Instead, the response is served up from your cache store.

You can tell the response caching middleware to take your query string parameters into account as such (like you did in your example):

[HttpGet(Name = Route.GetEtablissementsList)]
[HttpHead]
[ProducesResponseType(StatusCodes.Status200OK)]
[ResponseCache(Duration = 60, VaryByQueryKeys = new string[] {"Page", "Size"})]
public ActionResult<IEnumerable> GetEtablissements(
[FromQuery] Paging parameters)

As marvin.cache.headers automatically takes all query string parameters into account (and Page & Size are the only two), this will result in both middlewares working nicely together :)

Small tip: I'd suggest not using the response cache middleware. It's only a partial implementation of the Http Cache standard which tends to result in a less performant cache. It's better to use a separate cache server or CDN that correctly implements the Http Cache standard. If you use one of those approaches, all you'll need in your API is the marvin.cache.headers middleware - the cache server will take care of the rest.

Bonne chance! ;-)
